### PR TITLE
More unit tests

### PR DESCRIPTION
**Pull request by icecrime**
Refactored a bit and added a few more tests cases for registry v2.

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM!

**Comment by dmp42** [comment]
LGTM

**Comment by dmcgowan** [comment]
These tests do not pass for me, I will merge them in since the other tests do not pass and can try and get them to pass as a whole

**Comment by icecrime** [comment]
That's surprising: they pass locally for me (they are expected to fail on Drone as we need to update the image).

**Pull request merged**
